<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PF-ADS CMS</title>
</head>
<body>
  <div id="root"></div>

  <!-- Загружаем локальную версию -->
  <script src="/admin/cms.js"></script>
  
  <script>
    if (window.CMS) {
      CMS.init();
    } else {
      document.body.innerHTML = '<div style="padding: 40px; text-align: center;"><h2>Ошибка загрузки CMS</h2><p>Локальный файл не загружен</p></div>';
    }
  </script>
</body>
</html>
