backend:
  name: github
  repo: pf-ads/website        
  branch: main
  base_url: https://auth.pf-ads.com   
  auth_endpoint: /auth       

site_url: https://www.pf-ads.com       
display_url: https://www.pf-ads.com
logo_url: /images/logo.png

publish_mode: editorial_workflow

media_folder: "static/uploads"         
public_folder: "/uploads"              

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

local_backend: false                     
load_config_file: false                  

publish_events: true
