backend:
  name: github
  repo: pf-ads/website             
  branch: main
  base_url: https://api.github.com
  auth_type: token
  token: GITHUB_TOKEN              
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"

site_url: https://www.pf-ads.com
display_url: https://www.pf-ads.com
publish_mode: editorial_workflow

# === Место хранения изображений ===
media_folder: "images/uploads"     
public_folder: "/images/uploads"   

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"                  
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contact Page"
        name: "contact"
        file: "contact.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
