backend:
  name: github
  repo: AleksandrPepeslavtcev/pf-ads-site
  branch: main
  base_url: https://www.pf-ads.com
  site_url: https://www.pf-ads.com
  auth_type: implicit
  app_id: "Ov23liB9OZZ7mdtgK4HL"

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"
locale: "ru"
publish_mode: simple

collections:
  - name: "posts"
    label: "Посты блога"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата публикации", name: "date", widget: "datetime" }
      - { label: "Категории", name: "categories", widget: "list" }
      - { label: "Содержание", name: "body", widget: "markdown" }
